package io.github.paulanthonyreitz.reitzmmo.Custom_Recipes;

import java.util.Objects;

import io.github.paulanthonyreitz.reitzmmo.ConfigFiles.API;
import net.md_5.bungee.api.chat.BaseComponent;
import net.md_5.bungee.api.chat.ClickEvent;
import net.md_5.bungee.api.chat.ComponentBuilder;
import net.md_5.bungee.api.chat.HoverEvent;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.BookMeta;
import org.bukkit.inventory.meta.ItemMeta;

public class ReitzMMO_Book {
     public static void setLoginBook(Player p) {
          boolean kingMobsEnabled = API.specialMonsterConfig.getBoolean("kingMobsEnabled");
          boolean notoriousMobsEnabled = API.specialMonsterConfig.getBoolean("notoriusMobsEnabled");
          boolean devilishMobsEnabled = API.specialMonsterConfig.getBoolean("devilishMobsEnabled");
          boolean dumbMobsEnabled = API.specialMonsterConfig.getBoolean("dumbMobsEnabled");
          int kingMobsLV = API.specialMonsterConfig.getInt("kingMobsLVDifference");
          int notoriousMobsLV = API.specialMonsterConfig.getInt("notoriousMobsLVDifference");
          int devilishMobsLV = API.specialMonsterConfig.getInt("devilishMobsLVDifference");
          int dumbMobsLV = API.specialMonsterConfig.getInt("dumbMobsLVDifference");
          boolean specialMobGlowingEnabled = API.specialMonsterConfig.getBoolean("specialMonsterGlowEnabled");
          boolean specialMobSilentEnabled = API.specialMonsterConfig.getBoolean("specialMonsterSilentEnabled");
          int blocksPerMobLevel = API.monsterConfig.getInt("BLOCKS-PER-MOB-LEVEL");
          int zombieBaseHP = API.monsterConfig.getInt("ZOMBIE_BASE_HP");
          int wolfBaseHP = API.monsterConfig.getInt("WOLF_BASE_HP");
          int villagerBaseHP = API.monsterConfig.getInt("VILLAGER_BASE_HP");
          int squidBaseHP = API.monsterConfig.getInt("SQUID_BASE_HP");
          int spiderBaseHP = API.monsterConfig.getInt("SPIDER_BASE_HP");
          int snowmanBaseHP = API.monsterConfig.getInt("SNOWMAN_BASE_HP");
          int slimeBaseHP = API.monsterConfig.getInt("SLIME_BASE_HP");
          int skeletonBaseHP = API.monsterConfig.getInt("SKELETON_BASE_HP");
          int silverfishBaseHP = API.monsterConfig.getInt("SILVERFISH_BASE_HP");
          int sheepBaseHP = API.monsterConfig.getInt("SHEEP_BASE_HP");
          int rabbitBaseHP = API.monsterConfig.getInt("RABBIT_BASE_HP");
          int pigzombieBaseHP = API.monsterConfig.getInt("PIGZOMBIE_BASE_HP");
          int pigBaseHP = API.monsterConfig.getInt("PIG_BASE_HP");
          int mushroomcowBaseHP = API.monsterConfig.getInt("MUSHROOMCOW_BASE_HP");
          int magmacubeBaseHP = API.monsterConfig.getInt("MAGMACUBE_BASE_HP");
          int guardianBaseHP = API.monsterConfig.getInt("GUARDIAN_BASE_HP");
          int giantBaseHP = API.monsterConfig.getInt("GIANT_BASE_HP");
          int ghastBaseHP = API.monsterConfig.getInt("GHAST_BASE_HP");
          int endermiteBaseHP = API.monsterConfig.getInt("ENDERMITE_BASE_HP");
          int endermanBaseHP = API.monsterConfig.getInt("ENDERMAN_BASE_HP");
          int enderdragonBaseHP = API.monsterConfig.getInt("ENDERDRAGON_BASE_HP");
          int creeperBaseHP = API.monsterConfig.getInt("CREEPER_BASE_HP");
          int cowBaseHP = API.monsterConfig.getInt("COW_BASE_HP");
          int chickenBaseHP = API.monsterConfig.getInt("CHICKEN_BASE_HP");
          int cavespiderBaseHP = API.monsterConfig.getInt("CAVESPIDER_BASE_HP");
          int blazeBaseHP = API.monsterConfig.getInt("BLAZE_BASE_HP");
          int witchBaseHP = API.monsterConfig.getInt("WITCH_BASE_HP");
          int witherSkeletonBaseHP = API.monsterConfig.getInt("WITHERSKELETON_BASE_HP");
          int shulkerBaseHP = API.monsterConfig.getInt("SHULKER_BASE_HP");
          int pillagerBaseHP = API.monsterConfig.getInt("PILLAGER_BASE_HP");
          int illusionerBaseHP = API.monsterConfig.getInt("ILLUSIONER_BASE_HP");
          int evokerBaseHP = API.monsterConfig.getInt("EVOKER_BASE_HP");
          int ravagerBaseHP = API.monsterConfig.getInt("RAVAGER_BASE_HP");
          int batBaseHP = API.monsterConfig.getInt("BAT_BASE_HP");
          int drownedBaseHP = API.monsterConfig.getInt("DROWNED_BASE_HP");
          int zombievillagerBaseHP = API.monsterConfig.getInt("ZOMBIEVILLAGER_BASE_HP");
          int polarBearBaseHP = API.monsterConfig.getInt("POLARBEAR_BASE_HP");
          int wanderingTraderBaseHP = API.monsterConfig.getInt("WANDERINGTRADER_BASE_HP");
          int donkeyBaseHP = API.monsterConfig.getInt("DONKEY_BASE_HP");
          int llamaBaseHP = API.monsterConfig.getInt("LLAMA_BASE_HP");
          int salmonBaseHP = API.monsterConfig.getInt("SALMON_BASE_HP");
          boolean monsterNameplatesEnabled = API.monsterConfig.getBoolean("NAMEPLATES_ENABLED");
          boolean zombieNameplate = API.monsterConfig.getBoolean("ZOMBIE_NAMEPLATES_ENABLED");
          boolean wolfNameplate = API.monsterConfig.getBoolean("WOLF_NAMEPLATES_ENABLED");
          boolean villagerNameplate = API.monsterConfig.getBoolean("VILLAGER_NAMEPLATES_ENABLED");
          boolean squidNameplate = API.monsterConfig.getBoolean("SQUID_NAMEPLATES_ENABLED");
          boolean spiderNameplate = API.monsterConfig.getBoolean("SPIDER_NAMEPLATES_ENABLED");
          boolean snowmanNameplate = API.monsterConfig.getBoolean("SNOWMAN_NAMEPLATES_ENABLED");
          boolean slimeNameplate = API.monsterConfig.getBoolean("SLIME_NAMEPLATES_ENABLED");
          boolean skeletonNameplate = API.monsterConfig.getBoolean("SKELETON_NAMEPLATES_ENABLED");
          boolean silverfishNameplate = API.monsterConfig.getBoolean("SILVERFISH_NAMEPLATES_ENABLED");
          boolean sheepNameplate = API.monsterConfig.getBoolean("SHEEP_NAMEPLATES_ENABLED");
          boolean rabbitNameplate = API.monsterConfig.getBoolean("RABBIT_NAMEPLATES_ENABLED");
          boolean pigzombieNameplate = API.monsterConfig.getBoolean("PIGZOMBIE_NAMEPLATES_ENABLED");
          boolean pigNameplate = API.monsterConfig.getBoolean("PIG_NAMEPLATES_ENABLED");
          boolean mushroomcowNameplate = API.monsterConfig.getBoolean("MUSHROOMCOW_NAMEPLATES_ENABLED");
          boolean magmacubeNameplate = API.monsterConfig.getBoolean("MAGMACUBE_NAMEPLATES_ENABLED");
          boolean guardianNameplate = API.monsterConfig.getBoolean("GUARDIAN_NAMEPLATES_ENABLED");
          boolean giantNameplate = API.monsterConfig.getBoolean("GIANT_NAMEPLATES_ENABLED");
          boolean ghastNameplate = API.monsterConfig.getBoolean("GHAST_NAMEPLATES_ENABLED");
          boolean endermiteNameplate = API.monsterConfig.getBoolean("ENDERMITE_NAMEPLATES_ENABLED");
          boolean endermanNameplate = API.monsterConfig.getBoolean("ENDERMAN_NAMEPLATES_ENABLED");
          boolean enderdragonNameplate = API.monsterConfig.getBoolean("ENDERDRAGON_NAMEPLATES_ENABLED");
          boolean creeperNameplate = API.monsterConfig.getBoolean("CREEPER_NAMEPLATES_ENABLED");
          boolean cowNameplate = API.monsterConfig.getBoolean("COW_NAMEPLATES_ENABLED");
          boolean chickenNameplate = API.monsterConfig.getBoolean("CHICKEN_NAMEPLATES_ENABLED");
          boolean cavespiderNameplate = API.monsterConfig.getBoolean("CAVESPIDER_NAMEPLATES_ENABLED");
          boolean blazeNameplate = API.monsterConfig.getBoolean("BLAZE_NAMEPLATES_ENABLED");
          boolean witchNameplate = API.monsterConfig.getBoolean("WITCH_NAMEPLATES_ENABLED");
          boolean witherSkeletonNameplate = API.monsterConfig.getBoolean("WITHERSKELETON_NAMEPLATES_ENABLED");
          boolean shulkerNameplate = API.monsterConfig.getBoolean("SHULKER_NAMEPLATES_ENABLED");
          boolean pillagerNameplate = API.monsterConfig.getBoolean("PILLAGER_NAMEPLATES_ENABLED");
          boolean illusionerNameplate = API.monsterConfig.getBoolean("ILLUSIONER_NAMEPLATES_ENABLED");
          boolean evokerNameplate = API.monsterConfig.getBoolean("EVOKER_NAMEPLATES_ENABLED");
          boolean ravagerNameplate = API.monsterConfig.getBoolean("RAVAGER_NAMEPLATES_ENABLED");
          boolean batNameplate = API.monsterConfig.getBoolean("BAT_NAMEPLATES_ENABLED");
          boolean drownedNameplate = API.monsterConfig.getBoolean("DROWNED_NAMEPLATES_ENABLED");
          boolean zombievillagerNameplate = API.monsterConfig.getBoolean("ZOMBIEVILLAGER_NAMEPLATES_ENABLED");
          boolean polarBearNameplate = API.monsterConfig.getBoolean("POLARBEAR_NAMEPLATES_ENABLED");
          boolean wanderingTraderNameplate = API.monsterConfig.getBoolean("WANDERINGTRADER_NAMEPLATES_ENABLED");
          boolean donkeyNameplate = API.monsterConfig.getBoolean("DONKEY_NAMEPLATES_ENABLED");
          boolean llamaNameplate = API.monsterConfig.getBoolean("LLAMA_NAMEPLATES_ENABLED");
          boolean salmonNameplate = API.monsterConfig.getBoolean("SALMON_NAMEPLATES_ENABLED");
          int zombieSpeed = API.monsterConfig.getInt("ZOMBIE_SPEED");
          int wolfSpeed = API.monsterConfig.getInt("WOLF_SPEED");
          int villagerSpeed = API.monsterConfig.getInt("VILLAGER_SPEED");
          int squidSpeed = API.monsterConfig.getInt("SQUID_SPEED");
          int spiderSpeed = API.monsterConfig.getInt("SPIDER_SPEED");
          int snowmanSpeed = API.monsterConfig.getInt("SNOWMAN_SPEED");
          int slimeSpeed = API.monsterConfig.getInt("SLIME_SPEED");
          int skeletonSpeed = API.monsterConfig.getInt("SKELETON_SPEED");
          int silverfishSpeed = API.monsterConfig.getInt("SILVERFISH_SPEED");
          int sheepSpeed = API.monsterConfig.getInt("SHEEP_SPEED");
          int rabbitSpeed = API.monsterConfig.getInt("RABBIT_SPEED");
          int pigzombieSpeed = API.monsterConfig.getInt("PIGZOMBIE_SPEED");
          int pigSpeed = API.monsterConfig.getInt("PIG_SPEED");
          int mushroomcowSpeed = API.monsterConfig.getInt("MUSHROOMCOW_SPEED");
          int magmacubeSpeed = API.monsterConfig.getInt("MAGMACUBE_SPEED");
          int guardianSpeed = API.monsterConfig.getInt("GUARDIAN_SPEED");
          int giantSpeed = API.monsterConfig.getInt("GIANT_SPEED");
          int ghastSpeed = API.monsterConfig.getInt("GHAST_SPEED");
          int endermiteSpeed = API.monsterConfig.getInt("ENDERMITE_SPEED");
          int endermanSpeed = API.monsterConfig.getInt("ENDERMAN_SPEED");
          int enderdragonSpeed = API.monsterConfig.getInt("ENDERDRAGON_SPEED");
          int creeperSpeed = API.monsterConfig.getInt("CREEPER_SPEED");
          int cowSpeed = API.monsterConfig.getInt("COW_SPEED");
          int chickenSpeed = API.monsterConfig.getInt("CHICKEN_SPEED");
          int cavespiderSpeed = API.monsterConfig.getInt("CAVESPIDER_SPEED");
          int blazeSpeed = API.monsterConfig.getInt("BLAZE_SPEED");
          int witchSpeed = API.monsterConfig.getInt("WITCH_SPEED");
          int witherSkeletonSpeed = API.monsterConfig.getInt("WITHERSKELETON_SPEED");
          int shulkerSpeed = API.monsterConfig.getInt("SHULKER_SPEED");
          int pillagerSpeed = API.monsterConfig.getInt("PILLAGER_SPEED");
          int illusionerSpeed = API.monsterConfig.getInt("ILLUSIONER_SPEED");
          int evokerSpeed = API.monsterConfig.getInt("EVOKER_SPEED");
          int ravagerSpeed = API.monsterConfig.getInt("RAVAGER_SPEED");
          int batSpeed = API.monsterConfig.getInt("BAT_SPEED");
          int drownedSpeed = API.monsterConfig.getInt("DROWNED_SPEED");
          int zombievillagerSpeed = API.monsterConfig.getInt("ZOMBIEVILLAGER_SPEED");
          int polarBearSpeed = API.monsterConfig.getInt("POLARBEAR_SPEED");
          int wanderingTraderSpeed = API.monsterConfig.getInt("WANDERINGTRADER_SPEED");
          int donkeySpeed = API.monsterConfig.getInt("DONKEY_SPEED");
          int llamaSpeed = API.monsterConfig.getInt("LLAMA_SPEED");
          int salmonSpeed = API.monsterConfig.getInt("SALMON_SPEED");
          int zombieMinLevel = API.monsterConfig.getInt("ZOMBIE_MIN_LEVEL");
          int wolfMinLevel = API.monsterConfig.getInt("WOLF_MIN_LEVEL");
          int villagerMinLevel = API.monsterConfig.getInt("VILLAGER_MIN_LEVEL");
          int squidMinLevel = API.monsterConfig.getInt("SQUID_MIN_LEVEL");
          int spiderMinLevel = API.monsterConfig.getInt("SPIDER_MIN_LEVEL");
          int snowmanMinLevel = API.monsterConfig.getInt("SNOWMAN_MIN_LEVEL");
          int slimeMinLevel = API.monsterConfig.getInt("SLIME_MIN_LEVEL");
          int skeletonMinLevel = API.monsterConfig.getInt("SKELETON_MIN_LEVEL");
          int silverfishMinLevel = API.monsterConfig.getInt("SILVERFISH_MIN_LEVEL");
          int sheepMinLevel = API.monsterConfig.getInt("SHEEP_MIN_LEVEL");
          int rabbitMinLevel = API.monsterConfig.getInt("RABBIT_MIN_LEVEL");
          int pigzombieMinLevel = API.monsterConfig.getInt("PIGZOMBIE_MIN_LEVEL");
          int pigMinLevel = API.monsterConfig.getInt("PIG_MIN_LEVEL");
          int mushroomcowMinLevel = API.monsterConfig.getInt("MUSHROOMCOW_MIN_LEVEL");
          int magmacubeMinLevel = API.monsterConfig.getInt("MAGMACUBE_MIN_LEVEL");
          int guardianMinLevel = API.monsterConfig.getInt("GUARDIAN_MIN_LEVEL");
          int giantMinLevel = API.monsterConfig.getInt("GIANT_MIN_LEVEL");
          int ghastMinLevel = API.monsterConfig.getInt("GHAST_MIN_LEVEL");
          int endermiteMinLevel = API.monsterConfig.getInt("ENDERMITE_MIN_LEVEL");
          int endermanMinLevel = API.monsterConfig.getInt("ENDERMAN_MIN_LEVEL");
          int enderdragonMinLevel = API.monsterConfig.getInt("ENDERDRAGON_MIN_LEVEL");
          int creeperMinLevel = API.monsterConfig.getInt("CREEPER_MIN_LEVEL");
          int cowMinLevel = API.monsterConfig.getInt("COW_MIN_LEVEL");
          int chickenMinLevel = API.monsterConfig.getInt("CHICKEN_MIN_LEVEL");
          int cavespiderMinLevel = API.monsterConfig.getInt("CAVESPIDER_MIN_LEVEL");
          int blazeMinLevel = API.monsterConfig.getInt("BLAZE_MIN_LEVEL");
          int witchMinLevel = API.monsterConfig.getInt("WITCH_MIN_LEVEL");
          int witherSkeletonMinLevel = API.monsterConfig.getInt("WITHERSKELETON_MIN_LEVEL");
          int shulkerMinLevel = API.monsterConfig.getInt("SHULKER_MIN_LEVEL");
          int pillagerMinLevel = API.monsterConfig.getInt("PILLAGER_MIN_LEVEL");
          int illusionerMinLevel = API.monsterConfig.getInt("ILLUSIONER_MIN_LEVEL");
          int evokerMinLevel = API.monsterConfig.getInt("EVOKER_MIN_LEVEL");
          int ravagerMinLevel = API.monsterConfig.getInt("RAVAGER_MIN_LEVEL");
          int batMinLevel = API.monsterConfig.getInt("BAT_MIN_LEVEL");
          int drownedMinLevel = API.monsterConfig.getInt("DROWNED_MIN_LEVEL");
          int zombievillagerMinLevel = API.monsterConfig.getInt("ZOMBIEVILLAGER_MIN_LEVEL");
          int polarBearMinLevel = API.monsterConfig.getInt("POLARBEAR_MIN_LEVEL");
          int wanderingTraderMinLevel = API.monsterConfig.getInt("WANDERINGTRADER_MIN_LEVEL");
          int donkeyMinLevel = API.monsterConfig.getInt("DONKEY_MIN_LEVEL");
          int llamaMinLevel = API.monsterConfig.getInt("LLAMA_MIN_LEVEL");
          int salmonMinLevel = API.monsterConfig.getInt("SALMON_MIN_LEVEL");
          ItemStack book = new ItemStack(Material.WRITTEN_BOOK);
          BookMeta bookMeta = (BookMeta)book.getItemMeta();
          BaseComponent[] page1 = (new ComponentBuilder("ReitzMMO")).bold(true).event(new ClickEvent(ClickEvent.Action.OPEN_URL, "https://www.spigotmc.org/resources/reitzmmo.1159/")).event(new HoverEvent(HoverEvent.Action.SHOW_TEXT, (new ComponentBuilder("Go to the plugin website")).create())).create();
          BaseComponent[] page2 = (new ComponentBuilder("ReitzMMO Command Menu(Click Here)")).bold(false).event(new ClickEvent(ClickEvent.Action.RUN_COMMAND, "/reitz")).create();
          ((BookMeta)Objects.<BookMeta>requireNonNull(bookMeta)).spigot().addPage(new BaseComponent[][] { page1 });
          bookMeta.spigot().addPage(new BaseComponent[][] { page2 });
          bookMeta.setTitle("ReitzMMO");
          bookMeta.setAuthor("Paully104");
          book.setItemMeta((ItemMeta)bookMeta);
          p.getInventory().addItem(new ItemStack[] { book });
     }

     public static void removeLoginBook(Player p) {
          for (ItemStack b : p.getInventory().getStorageContents()) {
               try {
                    if (b.hasItemMeta() &&
                            b.getItemMeta() instanceof BookMeta) {
                         BookMeta meta = (BookMeta)b.getItemMeta();
                         if (Objects.<String>requireNonNull(meta.getAuthor()).equals("Paully104") && ((String)Objects.<String>requireNonNull(meta.getTitle())).equals("ReitzMMO"))
                              p.getInventory().remove(b);
                    }
               } catch (NullPointerException nullPointerException) {}
          }
     }
}
